---
- name: Check existing install (blackbox)
  register: blackbox_exporter_version_check
  failed_when: false
  changed_when: false
  check_mode: false
  ansible.builtin.shell: /usr/bin/blackbox-exporter --version 2>&1
  tags:
    - exporters
    - blackbox

- name: Fact version change (blackbox)
  ansible.builtin.set_fact:
    blackbox_exporter_version_changed: "{{ blackbox_exporter_version_check.rc != 0 or (blackbox_exporter_version_check.stdout_lines is defined and blackbox_exporter_version not in blackbox_exporter_version_check.stdout_lines[0]) | bool }}"
  tags:
    - exporters
    - blackbox

- name: Download release tarball (blackbox)
  when:
    - blackbox_exporter_version_changed
  ansible.builtin.unarchive:
    src: "{{ blackbox_exporter_download }}"
    dest: /usr/local/src
    remote_src: true
    owner: root
    group: root
  tags:
    - exporters
    - blackbox

- name: Copy exporter binary (blackbox)
  when:
    - blackbox_exporter_version_changed
    - not ansible_check_mode
  notify:
    - Restart blackbox-exporter
  ansible.builtin.copy:
    src: "/usr/local/src/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ blackbox_exporter_arch }}/blackbox_exporter"
    dest: /usr/bin/blackbox-exporter
    remote_src: true
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - exporters
    - blackbox

- name: Write general config (blackbox)
  notify:
    - Restart blackbox-exporter
  ansible.builtin.template:
    src: blackbox/config.j2
    dest: /etc/blackbox.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - exporters
    - blackbox

- name: Write default config (blackbox)
  notify:
    - Restart blackbox-exporter
  ansible.builtin.template:
    src: blackbox/default.j2
    dest: /etc/default/blackbox-exporter
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - exporters
    - blackbox

- name: Write service file (blackbox)
  notify:
    - Restart blackbox-exporter
  ansible.builtin.template:
    src: blackbox/service.j2
    dest: /etc/systemd/system/blackbox-exporter.service
    owner: root
    group: root
    mode: u=rx,g=r,o=r
  tags:
    - exporters
    - blackbox

- name: Start exporter service (blackbox)
  ansible.builtin.systemd:
    name: blackbox-exporter
    state: started
    daemon_reload: true
    masked: false
    enabled: true
  tags:
    - exporters
    - blackbox

- name: Remove install directory (blackbox)
  ansible.builtin.file:
    path: "/usr/local/src/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ blackbox_exporter_arch }}"
    state: absent
  tags:
    - exporters
    - blackbox

...
