---
- name: Restart node-exporter
  ansible.builtin.systemd:
    name: node-exporter
    state: restarted
    daemon_reload: true

- name: Restart blackbox-exporter
  ansible.builtin.systemd:
    name: blackbox-exporter
    state: restarted
    daemon_reload: true

...
